/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/server';
import { resend, APP_URL } from '@/lib/email';
import { BankShareEmail } from '@/emails/BankShareEmail';
import { render } from '@react-email/render';

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const serviceClient = createAdminClient();
    const body = await request.json();

    const { client_id, bank_id, bank_name, contact_email, note, expires_at } = body;

    // Validate broker owns the client
    const { data: brokerData, error: brokerError } = await (serviceClient as any)
      .from('brokers')
      .select('id, office_id, is_office_admin')
      .eq('user_id', user.id)
      .eq('is_active', true)
      .single();

    if (brokerError || !brokerData) {
      return NextResponse.json({ error: 'Broker not found' }, { status: 404 });
    }

    const broker_id = brokerData.id;
    const office_id = brokerData.office_id;
    const is_office_admin = brokerData.is_office_admin;

    // Verify broker has access to this client:
    // - direct ownership (client.broker_id === broker.id), OR
    // - office admin for the same office (office admins can manage all clients in their office)
    const { data: clientData, error: clientError } = await (serviceClient as any)
      .from('clients')
      .select('id, broker_id, office_id')
      .eq('id', client_id)
      .single();

    if (clientError || !clientData) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 });
    }

    const isOwner = (clientData as any).broker_id === broker_id;
    const isOfficeAdmin = is_office_admin && (clientData as any).office_id === office_id;

    if (!isOwner && !isOfficeAdmin) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    // Insert into bank_share_links — token is generated by the DB (uuid default gen_random_uuid())
    const { data: shareLink, error: shareLinkError } = await (serviceClient as any)
      .from('bank_share_links')
      .insert({
        client_id,
        broker_id,
        bank_id,
        bank_name,
        contact_email,
        note: note || null,
        expires_at,
      })
      .select('*')
      .single();

    if (shareLinkError || !shareLink) {
      console.error('[bank-share/create] Insert failed:', shareLinkError);
      return NextResponse.json({ error: 'Failed to create share link' }, { status: 500 });
    }

    const token: string = (shareLink as any).token;

    // Fetch broker's office for white_label
    const { data: officeData, error: officeError } = await (serviceClient as any)
      .from('offices')
      .select('name, white_label')
      .eq('id', (brokerData as any).office_id)
      .single();

    if (officeError || !officeData) {
      console.error('Office lookup failed:', officeError, 'office_id:', (brokerData as any).office_id);
      return NextResponse.json({ error: 'Office not found' }, { status: 404 });
    }

    const officeName = officeData.name;
    const whiteLabel = officeData.white_label as { logo_url?: string | null; primary_color?: string; email_from_name?: string } | null;

    // Fetch broker display name — non-fatal, fall back to email
    const { data: userData } = await (serviceClient as any)
      .from('users')
      .select('name')
      .eq('id', user.id)
      .single();

    const brokerName: string = (userData as { name?: string } | null)?.name ?? user.email ?? 'Mediador';
    const officeLogoUrl = whiteLabel?.logo_url ?? null;

    // Construct share URL
    const shareUrl = `${APP_URL}/bank-share/${token}`;

    // Send email
    const emailHtml = await render(
      BankShareEmail({
        officeName,
        officeLogoUrl,
        brokerName,
        note: note || null,
        shareUrl,
        expiresAt: expires_at,
        contactEmail: contact_email,
      })
    );

    const { data: emailData, error: emailError } = await resend.emails.send({
      from: `${officeName} <noreply@esteeve.com>`,
      to: contact_email,
      subject: `Pedido de análise de crédito — ${officeName}`,
      html: emailHtml,
    });

    if (emailError) {
      console.error('[bank-share/create] Resend error:', emailError);
    } else {
      console.log('[bank-share/create] Invite email sent, id:', emailData?.id);
    }

    // Log to audit_log
    await (serviceClient as any).from('audit_log').insert({
      action: 'bank_share_created',
      actor_user_id: user.id,
      target_type: 'bank_share_link',
      target_id: shareLink.id,
      metadata: {
        bank_name,
        contact_email,
      },
    });

    return NextResponse.json(shareLink);
  } catch (err) {
    console.error('Create bank share error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
